/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cardnr3: typeof import('./src/components/mainComponents/Cardnr3.vue')['default']
    Cardnr4: typeof import('./src/components/mainComponents/Cardnr4.vue')['default']
    ChartCard: typeof import('./src/components/mainComponents/ChartCard.vue')['default']
    HumidityCard: typeof import('./src/components/mainComponents/HumidityCard.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    PowerPriceCard: typeof import('./src/components/mainComponents/PowerPriceCard.vue')['default']
    PowerPriceChart: typeof import('./src/components/mainComponents/PowerPriceChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemperatureKnob: typeof import('./src/components/mainComponents/TemperatureKnob.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    WeatherWidget: typeof import('./src/components/mainComponents/WeatherWidget.vue')['default']
  }
}
