/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/mainComponents/HumidityCard copy 2.vue')['default']
    Cardnr3: typeof import('./src/components/mainComponents/Cardnr3.vue')['default']
    Cardnr4: typeof import('./src/components/mainComponents/Cardnr4.vue')['default']
    copy: typeof import('./src/components/mainComponents/HumidityCard copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HumidityCard: typeof import('./src/components/mainComponents/HumidityCard.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    WeatherWidget: typeof import('./src/components/mainComponents/WeatherWidget.vue')['default']
  }
}
