/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChartView: typeof import('./src/components/ChartView.vue')['default']
    DeviceData: typeof import('./src/components/DeviceData.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    PowerPriceCard: typeof import('./src/components/PowerPriceCard.vue')['default']
    PowerPriceChart: typeof import('./src/components/PowerPriceChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemperatureKnob: typeof import('./src/components/TemperatureKnob.vue')['default']
    TemperatureSlider: typeof import('./src/components/TemperatureSlider.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    WeatherWidget: typeof import('./src/components/WeatherWidget.vue')['default']
  }
}
